stages:
  generate_dataset:
    cmd: python -m cvproject3.dataset
    deps:
    - cvproject3/data.py
    - cvproject3/dataset.py
    outs:
    - data
  train:
    cmd: python -m cvproject3.train
    deps:
    - cvproject3/models.py
    - cvproject3/model_impls
    - cvproject3/train.py
    - data
    params:
    - train.batch_size
    outs:
    - models/best.pt
  eval:
    cmd: python -m cvproject3.eval
    deps:
    - cvproject3
    - models/best.pt
metrics:
- dvclive/eval/metrics.json
- dvclive/train/metrics.json
plots:
- dvclive/eval/plots/metrics:
    x: step
- dvclive/eval/plots/images
- dvclive/train/plots/metrics:
    x: step
- dvclive/train/plots/images
